name: wamp_client
description: A library for Dart WAMP client.
version: 0.1.1
homepage: https://github.com/kkazuo/dart-wamp-client
author: Koga Kazuo <obiwanko@me.com>

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  msgpack:
    git:
      url: https://github.com/FarHard112/msgpack-remastered.git
      ref: master # Specify the branch if needed, default is 'main'

dev_dependencies:
  test: ^1.25.5
