name: msgpack
description: MsgPack for Dart
version: 1.0.0  # Update the version to indicate this is a new, null-safe version
environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: "^1.0.0"  # Update to a null-safe version if necessary
